### ISSUE TITLE
Populate a Microsoft Template output used in Create SharePoint file results in a corrupt file.

### ISSUE THREAD

**Issue by DariusPica** [Azure/logicapps#1061]
### Describe the Bug with repro steps

1. Populate a Microsoft Template action used. The output of this action looks ok. It is a JSON that contains two fields, content-type and content.
2. Create SharePoint file action used. The output of Populate a Microsoft Template action now looks like a binary string and the action results in a corrupt docx file.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by jasper-war** [comment]
I am having exactly the same issue using the old designer in a Power Apps Flow. Last successful run was exactly 4 weeks ago. Since then, piping the output of the 'Populate a Microsoft Word template' to 'Create File' results in a corrupted document. The document can neither be opened in the desktop nor the online app.
