### ISSUE TITLE
Stateful and stateless workflows

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#128]
Are there plans to provide more information with regards to stateful and stateless workflows?

After watching the //BUILD/ video it's still not clear to me:
- How they differentiate and when to use what?
- If this is a local feature only or if that's coming to Azure Logic Apps runtime as well?

**Comment by rohithah** [comment]
The stateful workflows are durable where you can dehydrate the workflow state and rehydrate at a later time.  We enable this by persisting the state after every action execution. Also since we persist the state after every action, it can gracefully recover from failures and resume execution from the last checkpointed state. 

The stateless workflows use the same declarative programming model so that the associated tools can be used to develop the application. However, it runs completely in memory and the app state will not be dehydrated when running.  What this means is that stateless will not be durable, and cannot be long running.  So scenarios like webhook actions, or delays will not be supported.

As for scenarios, we are primarily enabling low code developer experience for building solutions for high throughput and low latency workloads. 

It would be great to know if you have scenarios where mode of execution is useful for consumption Logic Apps.

**Comment by tomkerkhove** [comment]
Thanks, that helps to get a better understanding - Are there plans to provide a matrix with all the connectors and in which mode they are supported?

**Comment by rohithah** [comment]
yes - we will have better guidance on what connectors can be used with stateless and when to use them.
