### ISSUE TITLE
Error in fetching connection keys

### ISSUE THREAD

**Issue by johndowns** [Azure/logicapps#130]
I'm trying to follow along with the video. I got everything installed and got as far as adding the 'Send an email (v2)' step. I created a resource group in the portal and added a v1 logic app, then set up a connection to the Office 365 Outlook connector in there.

When I went back to the v2 designer in VS Code, I was able to see that connection and configure the action to send an email. However when I save the workflow I get this error:

```
Error in fetching connection keys for /subscriptions/mysubscriptionid/resourceGroups/LogicAppsV2/providers/Microsoft.Web/connections/office365. StatusCodeError: 400 - {"error":{"code":"OperationNotAllowed","message":"The operation to list connection keys is not allowed for subscription 'mysubscriptionid'."}}
```

**Comment by rohithah** [comment]
Did you register you subscription with the Logic Apps team for accessing azure connectors? if not pls reply to your private preview invite with the subscription. Otherwise do let us know the subscriptionId (you can respond to the same invite email) and we can take a look at our side to see if we miss registering it.

**Comment by johndowns** [comment]
@rohithah Thank you, I think that must be the issue. I have asked for my subscription ID to be added.
