### ISSUE TITLE
Deploy to a Docker container  - Callback url for request triggers fails with InternalServerError

### ISSUE THREAD

**Issue by sd-suresh** [Azure/logicapps#151]
As documented https://github.com/Azure/logicapps/wiki/4.-Deploy-to-a-Docker-container, while trying to retrieve Callback url for request triggers fails with InternalServerError. 

{
  "error": {
    "code": "InternalServerError",
    "message": "Encountered internal server error. The tracking Id is '6cbca7c8-4074-4fb2-8b4f-a272bf933130'."
  }
}

I retrieved the MASTER_KEY as documented https://github.com/Azure/azure-functions-docker/issues/84 from Azure Storage account which was mentioned while creating the Docker image. 

Is anybody tried to deploy to a Docker container & faced above issue?

**Comment by shankarmaha** [comment]
You should be able to see the docker logs for troubleshooting 

![image](https://user-images.githubusercontent.com/4720931/90665600-2aaf3380-e244-11ea-84bb-dbb7aed94fe2.png)

I faced the same issue sometime before and was able to identify the issue. It turned out that the published code that i used to build the docker container had some old invalid code. 

Hope that's helpful

**Comment by sd-suresh** [comment]
@shankarmaha 

Is it possible to share your sample docker file? Are you referring Azure Storage Account connection string in your docker file or you are using "AzureWebJobsStorage": "UseDevelopmentStorage=true"

I tried with fresh logic app and still getting same error.

http://localhost:8081/runtime/webhooks/flow/api/management/workflows/MockAPI/triggers/manual/listCallbackUrl?api-version=2019-10-01-edge-preview&code=[masterKey.value]

{
  "error": {
    "code": "InternalServerError",
    "message": "Encountered internal server error. The tracking Id is '9c03e130-a133-4bd5-82fd-e5378d36f41b'."
  }
}

C:\Working\LogicAppAsFunctionApp\MockAPI>docker run -p 8081:80 mockapi:2
Starting OpenBSD Secure Shell server: sshd.
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.

I don't see any additional info in the container logs apart from above lines. 

![image](https://user-images.githubusercontent.com/15982000/90669082-bc756b80-e259-11ea-8942-fb433d3cc00c.png)

**Comment by JanneMattila** [comment]
`UseDevelopmentStorage=true` refers to well-known [addresses](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-well-known-account-name-and-key) e.g. http://127.0.0.1:10000/ so they are not routable from your container to your local laptop (unless I've misunderstood the above of course :-))

**Comment by sd-suresh** [comment]
@JanneMattila 

Correct. I see the container is correctly pointing to Azure Storage account only. 

![image](https://user-images.githubusercontent.com/15982000/90671439-64406880-e25d-11ea-8c14-f44ded127233.png)

**Comment by JanneMattila** [comment]
Just to double-check... @sd-suresh does it work now? Or do you still get the `InternalServerError`?

**Comment by sd-suresh** [comment]
@JanneMattila 

Still same InternalServerError

**Comment by tomkerkhove** [comment]
This sounds like a duplicate of #129

Can you try adding the `WEBSITE_HOSTNAME=localhost` & `AZURE_FUNCTIONS_ENVIRONMENT=Development` environment variables please? Then it should work.

Looks like it's not documented yet, can we do this please @rohithah? See https://github.com/Azure/logicapps/issues/129#issuecomment-664166008

**Comment by sd-suresh** [comment]
@tomkerkhove 

Thanks a lot. Yes that fixed the issue.

My docker file contains below statements.

FROM mcr.microsoft.com/azure-functions/dotnet:3.0.13614-appservice

ENV AzureWebJobsStorage="**Replace with Azure Storage Account Connection String**"

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \ AzureFunctionsJobHost__Logging__Console__IsEnabled=true

ENV WEBSITE_HOSTNAME=localhost

ENV AZURE_FUNCTIONS_ENVIRONMENT=Development

COPY ./bin/Release/netcoreapp3.1/publish/ /home/site/wwwroot

**Comment by tomkerkhove** [comment]
Just a note, you should not add your connection string in the Dockerfile but pass it when you run the container 😅

**Comment by sd-suresh** [comment]
@tomkerkhove 

That's correct. I will remove that line from docker file when i push it ACR and will set environment variable value in deployment pipeline.

**Comment by mbarqawi** [comment]
I had the same error and fixed by changing the docker file to the below 

FROM mcr.microsoft.com/azure-functions/dotnet:3.0.13614-appservice


ENV AzureWebJobsStorage "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal"
ENV AZURE_FUNCTIONS_ENVIRONMENT Development
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \ AzureFunctionsJobHost__Logging__Console__IsEnabled=true
ENV WEBSITE_HOSTNAME=localhost

COPY bin/Debug/netcoreapp3.1/publish/ /home/site/wwwroot

**Comment by namrathah7** [comment]
Hi, Can anyone of you please share the host.json and local settings file..I just can not get it to working and i keep getting 404 not found. Also how do we get the .csproj in the logic app project because when i create a logic app project it doesn't create a .csproj and the documentation has got the .csproj 
Here in the below snapshot you can see none of the functions are loaded
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]

Starting JobHost

info: Host.Startup[401]

Starting Host (HostId=94c4103059d3-2137340777, InstanceId=ea7669e9-1b1f-447b-b2e5-e1d59d9e51d9, Version=3.0.14492.0, ProcessId=19, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))

info: Host.Startup[314]

Loading functions metadata

info: Host.Startup[315]

0 functions loaded

info: Host.Startup[0]

Generating 0 job function(s)

warn: Host.Startup[0]

No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

info: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]

Initializing function HTTP routes

No HTTP routes mapped


info: Host.Startup[412]

Host initialized (58ms)

info: Host.Startup[413]

Host started (70ms)

info: Host.Startup[0]

Job host started

Hosting environment: Development

Content root path: /

Now listening on: http://[::]:80

Application started. Press Ctrl+C to shut down.

info: Host.General[316]

Host lock lease acquired by instance ID '000000000000000000000000201E3ED2'.
