### ISSUE TITLE
Error while deploying a logic app with azure connection

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#171]
I am now able to create a logic app with azure connection. This is working locally. However, when trying to deploy the logic app to azure, i get the below error. Could you please help me solve this? 

![image](https://user-images.githubusercontent.com/4720931/94283908-8c507500-ff49-11ea-8692-ba9a3fdb3b7b.png)

**Comment by rarayudu** [comment]
We are looking into this issue. Will share the updates.

**Comment by rarayudu** [comment]
We identified the issue and working on fixing this. Connections using NON-MSFT tenants will face this issue. Will update back once the fixes are deployed.

**Comment by rarayudu** [comment]
shankarmaha, we are going to deploy a hotfix starting Monday with first region being West Central US. Will update once we deploy to that region and you can try after that.

**Comment by shankarmaha** [comment]
Thanks @rarayudu

**Comment by nidpathak** [comment]
@shankarmaha We have applied the fix for this issue in West Central US. Can you please try creating a new logic app and new azure connection in the West Central US? If you run into any issue with error code 'ApiConnectionAccessPolicyTenantIdMismatch' while using existing connection, just create a new azure connection and that should fix it. Let us know if you have any questions or concerns.

**Comment by shankarmaha** [comment]
@nidpathak Many thanks. It is now working. 👍

**Comment by rarayudu** [comment]
The changes are deployed to all regions. You should be able to use connections in all regions now
