### ISSUE TITLE
Stateless workflow doesn't load Azure Connectors

### ISSUE THREAD

**Issue by sjwaight** [Azure/logicapps#185]
Note: this behaviour may be as intended but is undocumented.

OS: Windows 10
VS Code: 1.50.1
Logic Apps Preview Extensions: v0.0.4
Storage Emulator: 5.10

Repo Steps:

1. Create a new Logic Apps (Preview) project as per instructions.
2. Create a new Logic App in the project and select "Stateless" for type.
3. Right click on workflow.json and select "Use Connectors from Azure" - you receive confirmation they are enabled for the project.
4. Open workflow in Designer. The "Azure" tab is missing for Connectors.

* now *

1. Close Designer.
2. Edit worklow.json and change "kind" from "Stateless" to "Stateful".
3. Reload in the Designer and the Azure Connector tab is visible.

If Azure Connectors are not available for Stateless workflows then the option to use them should be removed from VS Code or an appropriate message shown to user.

**Comment by tonytang-microsoft-com** [comment]
Hi @sjwaight , the azure connectors are not available for triggers in stateless workflow. You should see it when you add an action. Please let us know if that's not the case. We will make sure it's documented if not.

**Comment by sjwaight** [comment]
OK, that's fine, but in VS Code I can select the workflow.json file and choose to enable them - ideally that option shouldn't show if the workload type is stateless.

**Comment by ecfan** [comment]
#preview

**Comment by tonytang-microsoft-com** [comment]
Hi @sjwaight , when workflow is stateless, you can also choose to use Azure connector as "actions", that's why the option is there. The azure tab will show up if you are adding "actions", but not "triggers".

**Comment by ecfan** [comment]
Hi @sjwaight,

This info is documented in the official doc sections below. To improve discovery and clarity, can you confirm the following or provide more context?

* As Tony mentioned, you're presented with the option to enable Azure-deployed connectors because you can still use Azure actions in stateless workflows, just not triggers. In that case, how would you expect the UX to inform you that you can't use Azure triggers?

* Which doc did you review to find this information?

  [ ] [Public Preview extension description page](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurelogicapps)
  [ ] [Public Preview Known Issues page](https://github.com/Azure/logicapps/blob/master/articles/logic-apps-public-preview-known-issues.md)
  [ ] [Doc page - Create stateful or stateless workflows in Visual Studio Code with the Azure Logic Apps (Preview) extension](https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code)

* Can we improve the existing info to make this clearer? For example, should the doc page state that Azure triggers won't be available for you to select in stateless workflows? Here's where the info appears in the doc page:

  ------

  * [Stateful versus stateless logic apps](https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#stateful-stateless)

    Stateless workflows currently support only actions for [managed connectors](https://docs.microsoft.com/azure/connectors/apis-list#managed-api-connectors), not triggers. To start your workflow, select the [built-in Request, Event Hubs, or Service Bus trigger](https://docs.microsoft.com/azure/connectors/apis-list#built-ins). For more information about unsupported triggers, actions, and connectors, see [Unsupported or unavailable capabilities](https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#unsupported).

  * [Unavailable or unsupported capabilities](https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#unsupported)

    To start your workflow, use the [built-in Request, Event Hubs, or Service Bus trigger](https://docs.microsoft.com/azure/connectors/apis-list#built-ins). Currently, enterprise connectors, on-premises data gateway triggers, webhook-based triggers, Sliding Window trigger, custom connectors, integration accounts, their artifacts, and their connectors aren't supported in this preview. The "call an Azure function" capability is unavailable, so for now, use the HTTP action to call the request URL for the Azure function.

    Stateless logic app workflows can only use actions for [managed connectors](https://docs.microsoft.com/azure/connectors/apis-list#managed-api-connectors), not triggers. Except for the previously specified triggers, stateful workflows can use both triggers and actions for managed connectors.

  ------

**Comment by sjwaight** [comment]
I think the documentation could certainly be improved in this way, though I appreciate this might be a preview limitation. The biggest challenge is what are "Connectors from Azure" vs ones that are bundled with the runtime - this seems to be a new concept with the new development / deployment model and is likely going to trip most people up coming from the PaaS service on Azure. 

I still think the VS Code Extension should be able to detect the workflow type and then optionally show / hide the context menu item "Use Connectors from Azure". At the moment it doesn't even error out so you have no way of identifying why there is an issue and will continuing trying again and again.

**Comment by ecfan** [comment]
The topic now states that although you enable managed connectors in Azure, triggers for those connectors won't appear for you to select in the designer:

https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code

**Comment by sjwaight** [comment]
Still a bit buried, but people (like me) should RTFM before jumping in and tyring :).
