### ISSUE TITLE
Logic App (Standard) Designer: "Previous failed" and "Next failed" on Foreach loop

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/logicapps#298]
I have created a _single-tenant_ Logic App (Standard) workflow that uses a `Foreach` loop. When executing the workflow both locally (using Visual Studio Code) and when deployed within the Azure Portal, the _Run history_ window shows the error messages _Next failed_ and _Previous failed_ on the Foreach loop. The Foreach loop and all steps within the loop seem to have executed successfully. Also the rest of the workflow executes fine:

![Screen Shot 2021-05-31 at 11 07 03](https://user-images.githubusercontent.com/24315199/120169520-582c0300-c200-11eb-80fa-edfdd3f2d2cb.png)

![Screen Shot 2021-05-31 at 11 12 43](https://user-images.githubusercontent.com/24315199/120170319-21a2b800-c201-11eb-8f07-313dae33286b.png)

**Comment by hongzli** [comment]
This is expected behavior. The "Next failed" button will jump to the next iteration that failed, while the "Next" button just goes to the next iteration. The purpose of this button is to speed up the investigation of failed iterations. For example, f you have 100 total iterations with a handful of failed iterations scattered throughout, it is much more convenient to click the "Next failed" button to jump to the next failure.

However, we appreciate the feedback and will work to design something more intuitive.

**Comment by hongzli** [comment]
@tonytang-microsoft-com , @sonalipai , @preetriti1 , @joechung-msft (FYI)

**Comment by joechung-msft** [comment]
+@Derek Li ***@***.***> and @Xiaowei ***@***.***>. The linked Github issue is feedback from a user who was confused by the "next failed" and "previous failed" buttons in the monitoring view pager.
