### ISSUE TITLE
Logic Apps Standard - no options for providing Consumer Group Name in the Event Hub Trigger connector

### ISSUE THREAD

**Issue by Nisha-D** [Azure/logicapps#344]
when we use the Event Hub Trigger in the Logic apps (consumptions), we see options to provide the Consumer Group Name, partition key, etc - but these options are not available in the Logic Apps Standard connectors.

![image](https://user-images.githubusercontent.com/20060578/127126655-5c2c5172-4f35-4a5e-82f4-7d462471ca29.png)

**Comment by ShreeDivyaMV** [comment]
There is no option currently to provide a consumer group in the Event Hub trigger. By default it would pick up events from $Default eventhub.
This functionality would be added in future, but we do not have an ETA yet. 
Please let us know if any other questions on this.

**Comment by edwardyhe** [comment]
Hi Nisha, this functionality (specifying consumer group name) has been added into the pipeline and will be available very soon. If there are other parameters that you require, please let us know and I will see if they can be added as well.

**Comment by Nisha-D** [comment]
Thanks Edward!

Can you please also add the parameters for the partition key, so that I can consume only the data for a specific partition.

Thanks.

**Comment by edwardyhe** [comment]
Hi Nisha, I have investigated this and unfortunately, support for specifying the partition key cannot be implemented by the Logic Apps team at this time. This is due to limits on the current API connections which are not controlled by our team. You could create an issue with the Azure Functions Team to add partition key information to their event hub trigger. When that functionality becomes available in Azure Functions, I will be able to bring the feature over to Logic Apps Standard. It is regretful that I cannot help you further at this moment!
