### ISSUE TITLE
LA Standard Trigger not woking- Health Status -Unhealthy

### ISSUE THREAD

**Issue by AnaghBhatt-TomTom** [Azure/logicapps#353]
LA Standard  Stateless workflow did not worked after deployment from VS Code.
Service Bus Queue is used as Trigger.
Error: Failed to Start Logic app run

**Comment by VeeraMS** [comment]
Hi @AnaghBhatt-TomTom,

These are probably due to one of the below. Could you check.

1. You might have not exported the local settings which contains the Built-In connector connection specific app settings while deploying from VS. Such as Service Bus connection string etc.
2. Check the workflow health status in the Logic App. If it shows unhealthy click on json view in the overview page and check the error to correct it accordingly.
3. You can login to Logic App kudu console and check the log files of the Function host to check the workflow validation errors.

**Comment by AnaghBhatt-TomTom** [comment]
Thanks Veera
It is resolved. Once again thanks for great help

**Comment by VeeraMS** [comment]
Great to hear and thanks for letting me know.
