### ISSUE TITLE
Deep link to workflow run

### ISSUE THREAD

**Issue by mdeery** [Azure/logicapps#358]
What is the url format for a hyperlink directly to a workflow run?

**Comment by ShreeDivyaMV** [comment]
@mdeery Below is the URL format you can use to GET the run details. Please make sure to authenticate the request.

https://management.azure.com/subscriptions/<SubscriptionID>/resourceGroups/<RGNAME>/providers/Microsoft.Web/sites/<LAName>/hostruntime/runtime/webhooks/workflow/api/management/workflows/<WorkflowName>/runs/<RunID>?api-version=2018-11-01&$expand=properties/actions,workflow/properties

You can also get a sample URL with enabling browser network logs by clicking F12 while checking the run history from the portal.

**Comment by mdeery** [comment]
Thanks for your reply. I was hoping that the link directed me to the rendered page on the Azure Portal not the json representation of the run. Like this in the old logic apps: https://yourazurecoach.com/2018/12/08/navigate-directly-to-the-logic-apps-run-details/

**Comment by ShreeDivyaMV** [comment]
@mdeery , sorry for the delay in getting back on this. I confirmed with the team and for Logic App Standard, there is no deep link available as of now. They are checking the feasibility of adding one and I will update the thread once there is some progress on it.

**Comment by ShreeDivyaMV** [comment]
@mdeery, could you provide more details on the use case for having this feature? This would help us to understand there requirement better and prioritize it

**Comment by mdeery** [comment]
It so operations can click on a link and go directly to the run details.

The logic app sends a message to email and/or Teams when an error occurs.
If we can derive the deep link from the following, operations can go
straight to the run details and instantly start to diagnose the problem.

"UserProperties": {
     "ResourceId": ***@***.***('resourceId')",
     "RuntimeId": ***@***.***()['run']['name']",
     "SourceName": ***@***.***()['name']",
     "SourceType": "Workflow"
}

**Comment by ShreeDivyaMV** [comment]
@mdeery, thank you.
The product group has created a work item to expose a public monitoring blade as a deep link for Logic app Standard. I don't have an ETA yet on it. But will keep you updated on the status.

Meanwhile if the requirement is urgent, there are two workarounds.
1. The operation team can manually navigate to the monitoring view (Obviously You might have thought about this already)
2. We can work with internal team to see if can invoke the existing monitoring view blade. Please bear in mind that the signature will change when we do the work to properly expose the blade as deep link and might require change in your implementation.

Please confirm if you would like to go with the workaround 2, so that I can take it forward with our internal team.

**Comment by mdeery** [comment]
Workaround 2 would be great. Let's go with that.

Thank you.

**Comment by mdeery** [comment]
Hi @shailesh-agre has this been abandoned?

**Comment by amrit-cloud-dev** [comment]
Below worked for me for Logic App Standard.

https://portal.azure.com/#view/Microsoft_Azure_EMA/WorkflowMonitorBlade/id/%2Fsubscriptions%2F@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}%2FresourceGroups%2F@{appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')}%2Fproviders%2FMicrosoft.Web%2Fsites%2F@{appsetting('WORKFLOWS_APP_NAME')}%2Fworkflows%2F@{workflow().name}/location/Australia%20Southeast/resourceId/%2Fworkflows%2F@{workflow().name}%2Fruns%2F@{workflow().run.name}/runProperties~/%7B%22trigger%22%3A%7B%7D%7D/isReadOnly~/false

**Comment by mdeery** [comment]
It works for me too. Thank you so much @amrit-cloud-dev
