### ISSUE TITLE
Recurrence Trigger not honoring the schedule

### ISSUE THREAD

**Issue by hugobarona** [Azure/logicapps#370]
Hi there.
I have a few logic apps that are using recurrence triggers to perform some tasks. I have configured the interval as 1 and frequency as hour, so it run every hour, and the start time I have 2021-08-29T20:00:00Z. 

The problem is that some of the executions are running 1 minute before the time, and I am using the current time inside the logic app to do a few queries and pull data, and it is not working because of this 1 minute.

I can workaround and implement some logic to round the time but I think it would worth if you could give it a try and replicate the issue.

Note: My LAs are running in North Europe if it is relevant.

![image](https://user-images.githubusercontent.com/5125006/132020770-d114fabf-8a2f-49e0-bb5c-beef0dc2df07.png)

Thank you.

**Comment by HarisAbdulkareem** [comment]
@hugobarona : It is by design and a documented behavior in Recurrence trigger.
Note: Sometimes, the timestamp for the triggered run might vary up to 1 minute from the scheduled time. If you need to pass the timestamp exactly as scheduled to subsequent actions, you can use template expressions to change the timestamp accordingly.
Here is the doc  reference: https://docs.microsoft.com/en-us/azure/connectors/connectors-native-recurrence#add-the-recurrence-trigger
