### ISSUE TITLE
SharePoint Trigger for "When an item is deleted" requires Site Collection Admin role?

### ISSUE THREAD

**Issue by gcmlpfaltaher** [Azure/logicapps#412]
Why does the SharePoint List trigger for "When an item is deleted" require the Site Collection Admin role when one can delete a row item using a less-permissive role in a SharePoint site?

When an item is deleted (Trigger): https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-an-item-is-deleted

As you can see in the below link, Delete item doesn't require the same level of permissions. 
Delete item (Action): https://docs.microsoft.com/en-us/connectors/sharepointonline/#delete-item

Given that you need to point to a specific list for the "When an item is deleted" trigger, why can't list-specific permissions of the built-in "Contribute" Permission level be enough to trigger in this scenario?  Site Collection Admin role is extremely permissive.

Contribute Permission Level: Can view, add, update, and delete list items and documents.
- List Permissions:
   - Delete items - Delete items from a list and documents from a document library

**Comment by swakMS** [comment]
As of now Trigger operation itself requires Flow owner to have Site Collection Admin role to run. If you would like to request the feature you may provide the feedback at the below link. 
https://feedback.azure.com/forums/287593-logic-apps/

**Comment by gcmlpfaltaher** [comment]
@swakMS - the question is why it requires that?  I noted above that I understood what role it needs.  Can you engage the product group to ask the reasoning behind it when the Contribute permission allows one to view deleted items?

**Comment by fs366e2spm** [comment]
Any update on this?

**Comment by swakMS** [comment]
Contribute permissions cannot see ALL deleted items- for those the user didn’t have access to before they were deleted.
Today Deleted items trigger returns ALL deleted items on the list. Due to internal implementation we can’t easily say whether current user had permission to deleted item after the item is deleted as this information is not available. So Deleted trigger is limited to only Site Admins to avoid the item-level permission check.
