### ISSUE TITLE
Issue with session enabled stateless workflow with peek-lock connector

### ISSUE THREAD

**Issue by sneha-sri-koduru** [Azure/logicapps#459]
1.	Expected behavior :
        Increment of delivery count of the message in service bus when not settling(complete/abandon) it in the logic app.
[reference link](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions#impact-of-delivery-count)
2.	Actual behavior:
        Delivery count is not being incremented 
3.	We are using built-in connector in preview, with peek-lock, and sessions enabled. 
4.	The Service Bus is locked down with Private Endpoints and has session enabled Topic subscriptions.
5.	As a temporary workaround we are explicitly handling the errors by completing/abandoning the message to increase the delivery count in the service bus so that it will not read the same message infinite number of times.

**Comment by alexkarcher-msft** [comment]
Hello Sneha,

This is by design in Service bus. Session enabled queues and topics do not increment the delivery account if no action is taken on the message. See this doc for more information: https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions#impact-of-delivery-count

Thanks,
Alex
