### ISSUE TITLE
Service bus connector with Managed Identity auth does not work in VSCode

### ISSUE THREAD

**Issue by mark-abrams** [Azure/logicapps#708]
### Describe the Bug

I have a Standard Logic App that writes a message to an Azure Service Bus topic using the "Send Message" built-in connector. The workflow uses a connection string for the connection to Service Bus and everything works.

However, I want to switch the authentication from the Logic App to Service bus to Managed Identity so I no longer have to maintain the connection string in configuration. Based on what I can see in the [Microsoft documentation](https://learn.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity?tabs=standard), and in the Azure Portal, Managed Identity authentication for the Service Bus built-in connector is no longer in Preview.

I have updated the _connection.json_ to use Managed Identity:

```
"service-bus-int01": {
  "displayName": "service-bus-int01",
  "parameterValues": {
    "authProvider": {
      "Type": "ManagedServiceIdentity"
    },
   "fullyQualifiedNamespace": "@appsetting('ServiceBus-int01-FullyQualifiedNamespace')"
  },
  "serviceProvider": {
    "id": "/serviceProviders/serviceBus"
  }
}
```

And added this to the _local.settings.json_:

```
"ServiceBus-int01-FullyQualifiedNamespace": "my-servicebus-namespace.servicebus.windows.net"
```

This configuration works perfectly when the Logic App runs in Azure, but does not work when running in VS Code in a local development environment. When the "Send Message" action is run, I get this error in the run history:

_ConnectionReferenceInvalid. The provided connection name 'service-bus-int01' for type 'ServiceProvider' has invalid 'authProvider' section. Managed identity is either not enabled or misconfigured on the Logic App. Please enable or repair managed identity before use._

### Plan Type

Local

### Steps to Reproduce the Bug or Issue

- Install the latest version of the _Azure Logic Apps (Standard) extension_ for VS Code (v1.0.45).
- Create a workflow that includes a HTTP trigger and an action to send a message to a Service Bus topic. Use a built-in connector and select the Managed Authentication option for the connection.
- Make sure the fully-qualified name of the Service bus namespace is correct in the _local.settings.json_.
- Run the workflow in VS Code and trigger the workflow by sending a HTTP request.
- The workflow fails when sending the message to the topic.

### Workflow JSON

```json
This is the Service Bus action definition:

              "Send_Member": {
                  "type": "ServiceProvider",
                  "inputs": {
                      "parameters": {
                          "entityName": "customer-topic",
                          "message": {
                              "contentData": "@outputs('Compose_Member')",
                              "contentType": "application/json",
                              "sessionId": "@triggerBody()?['customerId']",
                              "userProperties": {
                                  "operation": "@variables('operation')"                                                            
                              },
                              "messageId": "@triggerBody()?['id']",
                              "label": "member.@{variables('operation')}.@{body('Parse_Customer')?['header']?['customerId']}"
                          }
                      },
                      "serviceProviderConfiguration": {
                          "connectionName": "service-bus-int01",
                          "operationId": "sendMessage",
                          "serviceProviderId": "/serviceProviders/serviceBus"
                      }
                  }
              }
```

### Screenshots or Videos

This is the error I get in the Service Bus action when looking at the run history in VSCode:

![image](https://user-images.githubusercontent.com/66829458/214263461-fa1f5dc6-fd0a-4d35-8bd5-48140d677ecf.png)

The error is: _ConnectionReferenceInvalid. The provided connection name 'service-bus-int01' for type 'ServiceProvider' has invalid 'authProvider' section. Managed identity is either not enabled or misconfigured on the Logic App. Please enable or repair managed identity before use._

This is my installed Azure Logic Apps (Standard) extension:

![image](https://user-images.githubusercontent.com/66829458/214271227-46894023-128c-40b7-ab9e-d6c04f0a7d8f.png)

### Additional context

Since the connection to Service Bus using Managed Identity works when running in Azure, I am assuming that the issue lies with the Azure Logic Apps (Standard) extension that runs in VS Code and the functions runtime?

AB#16874288

**Comment by rohithah** [comment]
managed identity does not work when running locally. you need to have your logic app running on a Logic App resource with managed identity enabled for MI to work here.

you can use parameters.json file to parameterize your app so that the app uses connection string for auth locally and then have MI when running in cloud

**Comment by LogicAppUnit** [comment]
Hi, thanks for the comment. This seems like a limitation that needs to be made much clearer, and ideally fixed. Are there any plans to fix this?

Azure Functions support Managed Identity when using a Service bus trigger and bindings and this works when running in Azure and when running locally. When running locally, the Function uses the identity of the Azure account that is configured in VS Code, I was hoping that Logic Apps and the Service Bus connector would work in the same way.

What is the best way to request this feature? I'm sure that many people would be interested in this so that Logic Apps running locally work in the same say as Logic Apps running in Azure.

You say that _you can use parameters.json file to parameterize your app_, but what value am I supposed to use for the `authProvider.Type`  when I want to use a connection string?

**Comment by mark-abrams** [comment]
Hi, thanks for the comment. This seems like a limitation that needs to be made much clearer, and ideally fixed. Are there any plans to fix this?

Azure Functions support Managed Identity when using a Service bus trigger and bindings and this works when running in Azure and when running locally. When running locally, the Function uses the identity of the Azure account that is configured in VS Code, I was hoping that Logic Apps and the Service Bus connector would work in the same way.

What is the best way to request this feature? I'm sure that many people would be interested in this so that Logic Apps running locally work in the same say as Logic Apps running in Azure.

You say that _you can use parameters.json file to parameterize your app_, but what value am I supposed to use for the `authProvider.Type` when I want to use a connection string?

**Comment by gbd77rc** [comment]
Yeah, just ran into this as well.  I thought logic apps were supposed to be low/no code.  I am having to create multiple connections to servicebus in the same workflow.  One is for a trigger for messages in a queue and others for sending of messages to different queues in the same servicebus.  The visual studio code extension only accepts Connection String or AD OAuth, but the web UI accepts MI.   Azure Function was a lot easier to configure and use with MI in both VS Code and web portal.  My main reason for using the VS Code is because the Web Portal does not save the workflow with validation errors, but the message indicates it has saved it even if there are errors.  So lost a lot of work today with one thing or another.

So how do we use the parameters.json file for MI and how will this interact with parameters in the workflow when we deploy it?
