### ISSUE TITLE
Cannot start the workflow designer in VS Code

### ISSUE THREAD

**Issue by tilicon** [Azure/logicapps#716]
### Describe the Bug

I'm developing Logic Apps in VS Code on a _**Mac**_. Starting today I cannot load the workflow designer.

When I try to open a workflow using the context menu "Open in Designer" I get the usual message `"Starting workflow design time api. It might take a few seconds."`. In the output window I can see the following:

```
[2023-01-31T13:27:44.554Z] A host error has occurred during startup operation 'c2a7523a-39b6-4371-b479-365d12600950'.
[2023-01-31T13:27:44.554Z] Microsoft.WindowsAzure.ResourceStack: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libadvapi32.dll, 0x0001): tried: 'libadvapi32.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibadvapi32.dll' (no such file), '/usr/lib/libadvapi32.dll' (no such file, not in dyld cache), 'libadvapi32.dll' (no such file), '/usr/local/lib/libadvapi32.dll' (no such file), '/usr/lib/libadvapi32.dll' (no such file, not in dyld cache).
Value cannot be null. (Parameter 'provider')
2:41:46 PM: Error: connect ECONNREFUSED 127.0.0.1:8000
2:42:44 PM: Running command: "func host start --port 8000"... 
```

I can also see that a `func` process is being started and then quickly terminated when looking in the Activity Monitor.

This has been reproduced on several MacBooks, using Intel (Core i7) as well as Apple (M1 Pro) silicon. Same result.

Yesterday, January 30th, this was working fine. Today on Jan 31, it's not.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Open any logic app standard project
2. Try to open a workflow by right-clicking on a "workflow.json" file and then select "Open in Designer"
3. View output pane (Shift+CMD+U on Mac)

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

![Screenshot 2023-01-31 at 15 11 56](https://user-images.githubusercontent.com/7198461/215784126-af9ebff8-a8f0-4980-87b3-9cad500e1d5f.png)

AB#16959559

**Comment by J-Cat** [comment]
FYI--if you want the designer to continue working, you also have to update the host.json in workflow-designtime as well.

**Comment by tamaw** [comment]
Changing the `ExtensionBundle.Workflow` version has worked for me as a workaround for this issue.

**Comment by J-Cat** [comment]
Yes, but if you are running your Logic Apps in Docker containers (because you are supposed to be able to run these anywhere), then this is a massive problem as the production deployments break if the containers are restarted.

**Comment by tilicon** [comment]
The workaround works for me as well, thanks @J-Cat!

I've only updated the hosts file in workflow-designtime since my main issue is local editing of workflows.

**Comment by J-Cat** [comment]
I'm going to add here, that you can override the setting in your host.json file by setting an environment variable.

So if using Linux (or WSL2, or MacOS, or in a Linux Docker container), just make sure to set the following environment variable and it will override what is in the host.json.

export AzureFunctionsJobHost__extensionBundle__version="[1.*, 1.2.18)"

you can set this in your ~/.profile or ~/.bashrc or by creating a file in /etc/profile.d/ if you want to apply for everyone.

For our Kubernetes environments we can actually just update this through our ConfigMap, or Secrets

**Comment by axiomitdavid** [comment]
I seem to have deleted the older versions of 

"Microsoft.Azure.Functions.ExtensionBundle.Workflows"

Is there a way to force it to download?  

I updated the hosts.json with the 1.0.0, 1.2.18 but still downloads 1.3.7

**Comment by axiomitdavid** [comment]
I re-read this thread, only updated hosts.json in workflow-designtime and it's working for now.

Thanks for the valuable info!

**Comment by ccastrotrejo** [comment]
Hi all, thanks for raising this issue and for collaborating on the thread. I am able to repro the issue and will update you as soon as this is fixed. Please keep using the workaround stated above

**Comment by axiomitdavid** [comment]
> Hi all, thanks for raising this issue and for collaborating on the thread. I am able to repro the issue and will update you as soon as this is fixed. Please keep using the workaround stated above

Any timeframe for a fix?  Adding a new workflow to an existing Logic App resets the version string in hosts.json.

**Comment by J-Cat** [comment]
> Any timeframe for a fix? Adding a new workflow to an existing Logic App resets the version string in hosts.json.

I agree way too long of a wait so far, since it broke things in production on people, but use the fix I found and documented above of setting the environment variable.  That way it is easier to setup temporarily now and remove for all logic apps later once it is finally fixed.

**Comment by ccastrotrejo** [comment]
Hi all, sorry for the late response. The fix is released, and you should be able to remove the workaround and please update the extension to the latest version and remove the older extension bundles. The new extension bundle that you should get downloaded it's the 1.8.9

**Comment by HLChucky** [comment]
Hi - this appears to still be happening for me. I'm running in a Dev Container. 1.8.9 is downloaded, and my extension bundle looks like this:

"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
}

However, I'm still getting the following error:

Value cannot be null. (Parameter 'provider')
[2023-04-03T07:31:34.377Z] Host unavailable after check. Returning error.
7:34:48 AM: Error: connect ECONNREFUSED 127.0.0.1:8000

**Comment by axiomitdavid** [comment]
Need to re-open this.  Issue is now occurring with new Extension version 1.11.15

9:47:14 AM: Running command: "func host start --port 8003"...

Azure Functions Core Tools
Core Tools Version:       4.0.5095 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.5.20396

[2023-04-13T23:47:17.810Z] A host error has occurred during startup operation '9d2345e3-1adc-4fd7-9da4-f69e61c38c5b'.
[2023-04-13T23:47:17.810Z] Microsoft.Azure.Workflows.EventSource.Edge: The type initializer for 'Microsoft.Azure.Workflows.Common.Logging.FlowLog' threw an exception. Microsoft.WindowsAzure.ResourceStack: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libadvapi32.dll, 0x0001): tried: 'libadvapi32.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibadvapi32.dll' (no such file), '/usr/lib/libadvapi32.dll' (no such file, not in dyld cache), 'libadvapi32.dll' (no such file), '/usr/local/lib/libadvapi32.dll' (no such file), '/usr/lib/libadvapi32.dll' (no such file, not in dyld cache).
Value cannot be null. (Parameter 'provider')

**Comment by ccastrotrejo** [comment]
Hey @axiomitdavid thanks for letting us know this keeps happening in the new version. We will work on fixing it.

**Comment by axiomitdavid** [comment]
I'm trying to specify

  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 1.8.9)"

But this results in the broken 1.3.7 extension being downloaded.  

I've reverted to 1.2.18 as per the original workaround for this issue. Which is working.

For those just stumbling upon this issue:

You need to update host.json in **both** workflow-designtime and in the project level host.json

Change 

"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2..0.0)"
  },

to 

"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 1.2.18)"
  },

This should allow editing and running your workflows locally while the issue is worked on.

**Comment by jason-chong** [comment]
On Mac OS still getting this error. Used the workaround above and that resolved the error.
