### ISSUE TITLE
Scope takes more time to complete but not the underlying actions.

### ISSUE THREAD

**Issue by mhireholi** [Azure/logicapps#760]
### Describe the Bug

The scope shape takes more time to complete than the underlying actions - see screenshot

![las-bug-scope-02](https://user-images.githubusercontent.com/40304643/233161445-afaa1827-0832-4666-881a-56a46a07188c.jpg)

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Not sure

### Screenshots or Videos

![las-bug-scope-02](https://user-images.githubusercontent.com/40304643/233161465-d5848355-9be5-4d5e-8393-2322e9f31f11.jpg)

AB#22032283

**Comment by VeeraMS** [comment]
@mhireholi ,
Is it consumption or Standard Logic App?

If its Consumption Logic App, this could be because of noisy Neighbours the compute environment will be over utilized and might cause performance issues. However, this should be there only for sometime and should be handled by other workers in the backend.

If its Logic App standard, it is possible when you are doing load testing, or your App is over utilizing the App service plan resources. You can try scaling up to higher plans .
