### ISSUE TITLE
Switch case issue

### ISSUE THREAD

**Issue by Ramapreethi123** [Azure/logicapps#785]
### Describe the Bug with repro steps

1. Go to Logic app Standard
2. Insert a switch case with one case and a default
3. The flow goes to both case and default

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Browser

All

AB#24109867

**Comment by BBlesan** [comment]
Hello Preetriti1,

I have contacted Satyajith on teams call and we had a discussion of the issue.

Here is the Switch expression used:
![image](https://github.com/Azure/logicapps/assets/129366856/d6b5e4b3-2832-47c5-bb37-c8f74d97e45d)
Where the Variable referred is a string as below
![image](https://github.com/Azure/logicapps/assets/129366856/c8ac0a8f-3bcf-403c-a004-cfff1694e937)

The Case expression used is an hardcoded number as String literal, as shown below:
![image](https://github.com/Azure/logicapps/assets/129366856/6e2f1138-2eb9-49b7-b422-4bf40e06555e)

Everything works fine when the workflow is saved for the first time.

When the designer is reloaded, 
The new designer is not preserving the double quotes in the case expression.
So when the workflow is saved again the case expression has an Integer rather than a String.
Which results in the runtime error as below, due to the mismatch in dataype of Switch (String) and Case values (Integer). 
![image](https://github.com/Azure/logicapps/assets/129366856/e8f1ea2b-b111-42d4-894e-b898d7b831a9)

Whereas, the Old designer is preserving the double quotes, which don't change the datatype on reloading.


_New Designer when reloaded don't preserve quotes for number as Strings_
![image](https://github.com/Azure/logicapps/assets/129366856/1e1e3dce-321a-4e04-9752-6c129a6d2a20)

_Old Designer(using callback url aka.ms/lafallback) when reloaded preserves quotes_
![image](https://github.com/Azure/logicapps/assets/129366856/399abd75-d2ac-4f4c-9218-a05a28fa9bd3)


Hence the Issue: New Designer when reloaded don't preserve quotes for number as Strings, which changes the datatype of the value.
