### ISSUE TITLE
DocuSign Demo connections no longer working

### ISSUE THREAD

**Issue by gschultz125** [Azure/logicapps#936]
### Describe the Bug with repro steps

1. Add an DocuSign Demo action. 
2. Use existing or create new connection.
3. When using existing conneciton, the account field is blank. 
4. When creatign new connection receive unknown error. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

<img width="303" alt="01-github-no-connections-in-action" src="https://github.com/Azure/LogicAppsUX/assets/141440231/20a77c7e-4356-4fcc-98e0-48189fb59cfd">
<img width="308" alt="02-github-add-new-connection-in-action" src="https://github.com/Azure/LogicAppsUX/assets/141440231/62156a02-fbb1-4e9b-9919-6ca1eaa9cd80">
<img width="276" alt="03-github-add-new-connection-sign-in" src="https://github.com/Azure/LogicAppsUX/assets/141440231/6bddeb78-8f1a-406f-b95f-db05d09678b9">
<img width="306" alt="04-for-github-unknown-error" src="https://github.com/Azure/LogicAppsUX/assets/141440231/ec60b0a0-06a7-4acc-b2c5-5ff423f4c234">

### Browser

Edge

### Additional context

DocuSign Demo connections were working on Monday 12/4. Started noticing the connections stopped working on Thursday 12/7. We have also filed a support case with DocuSign. 

AB#26134259

**Comment by tonytang-microsoft-com** [comment]
@gschultz125 I can't repro this from our side. We need more data in order to help investigate this issue. Could you please file a support ticket on Logic Apps from portal? If possible, see if there's any console, or network errors. Plese fill out the information in the support ticket and those data will help us dig up the loggs from our side. Our support engineer will reach out to you to collect detailed data if needed.
