### ISSUE TITLE
When running the Workflow it is picking up the Older version of the code. Is the workflow code cached? 

### ISSUE THREAD

**Issue by skoluguri** [Azure/logicapps#960]
### Describe the Bug with repro steps

We have Salesforce connector on a Workflow.
When an object is created on Salesforce, workflow gets triggered.
I see in the Run History logs, the steps are referring to an older version of the workflow code.
I have checked the workflow code and designer, it has the latest code.
Need help in troubleshooting and fixing the issue.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by dcartamantiglia** [comment]
The issue is still alive.
I've checked on the wwwroot and the workflow.json is updated but the service is still running the previous version

**Comment by thinkOfaNumber** [comment]
When this has happened to me, it's because there is an error in the workflow.json. Unfortunately you can deploy broken workflow.json code successfully, but it just won't run. I don't know your specific scenario, but I check it by doing the following:

1. go to the designer on the azure portal (web) for the workflow in question
2. make a benign change - e.g. add a space or newline to a parse action or something like that
3. save the designer

If you have an error somewhere else, you should now get an error message about saving the workflow. 

Hope this helps!

**Comment by skoluguri** [comment]
The issue got resolved. The workflow had validation errors which was not clear during the deployment. For some reason it was not accepting parameters. I had to remove them and redeploy without using parameters. 
I was using ADO pipelines to deploy the code since editing the workflow on the designer is restricted in my case. 
@thinkOfaNumber thank you for the response.
